
shared:
  valid_loader: &valid_loader valid
  minimize_valid_metric: &minimize_valid_metric False
  valid_metric: &valid_metric accuracy
  batch_size: &bs 128
  num_workers: &nw 32

# --------------------------------------------------------------------

args:
  logdir: &logdir './logs/catalyst-config-api'
  seed: 42

# --------------------------------------------------------------------

runner:
  _target_: MyConfigRunner
  input_key: &model_input "features"
  output_key: &model_output "logits"
  target_key: &model_target "targets"
  loss_key: &model_loss "loss"

engine:
  _target_: DeviceEngine
  device: "cuda:1"

model:
  _target_: MyModel
  num_classes: 10

loggers:
  console:
    _target_: ConsoleLogger

  tensorboard:
    _target_: TensorboardLogger
    logdir: *logdir
    use_logdir_postfix: True

# --------------------------------------------------------------------

stages:
  stage_0:
    num_epochs: 3

    loaders: &loaders
      # default kwargs for `runner.get_loaders`:
      batch_size: *bs
      num_workers: *nw

    criterion:
      _target_: CrossEntropyLoss

    optimizer:
      _target_: Adam

    callbacks: &callbacks
      accuracy:
        _target_: AccuracyCallback
        input_key: *model_output
        target_key: *model_target
        num_classes: 10
      loss:
        _target_: CriterionCallback
        input_key: *model_output
        target_key: *model_target
        metric_key: *model_loss
      optimizer:
        _target_: OptimizerCallback
        metric_key: *model_loss
        # grad_clip_fn: clip_grad_value_
        # grad_clip_params:
        #   clip_value: 1.0
      # scheduler:
      #   _target_: SchedulerCallback
      #   loader_key: *valid_loader
      #   metric_key: *valid_metric
      saver:
        _target_: CheckpointCallback
        logdir: *logdir
        loader_key: *valid_loader
        metric_key: *valid_metric
        minimize: *minimize_valid_metric
        use_logdir_postfix: True
        load_on_stage_start: best
      verbose:
        _target_: TqdmCallback

  stage_1:
    num_epochs: 3

    loaders: *loaders

    criterion:
      _target_: CrossEntropyLoss

    optimizer:
      _target_: SGD

    callbacks: *callbacks
